services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '0.0.0.0:2181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '0.0.0.0:9092:9092'

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: QWp3dtwmT*m7hHQqdzuo82jYuuL@Ls
    ports:
      - '0.0.0.0:27017:27017'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-smart-envios
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:QWp3dtwmT%2Am7hHQqdzuo82jYuuL%40Ls@mongodb:27017/trackingdb?authSource=admin
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: tracking-events
      CARRIERS_API_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..."
      API_URL_CARRIERS: "http://api.carriers.com.br/client/Carriers"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - mongodb
      - kafka
      - redis
